name: Pull Request

on:
    pull_request:
        branches: main

jobs:
   first-job:
    runs-on: ubuntu-lates
    steps:
      - name: first step
        run: echo "first step"

      - name: second step
        run: echo "second step"   
