name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      script:
        required: true
        type: string

jobs:
  setup-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: npm run ${{ inputs.script }}
